### ISSUE TITLE
ローカル環境の構成をserverless-offlineとserverless-dynamodb-localを使った形に変更する

### ISSUE THREAD

**Issue by keita-nishimoto** [keita-nishimoto/aws-serverless-prototype#55]
## 完了の定義
- 表題の件が実行されている事

## メモ
https://github.com/keita-nishimoto/aws-serverless-prototype/issues/50 で対応出来なかった部分に再チャレンジ。

デバッガーも使えるようにしておきたい。
- http://qiita.com/teradonburi/items/3ab06f04edbdbdcb02a7

**Comment by keita-nishimoto** [comment]
デバックは [こちら](https://github.com/keita-nishimoto/aws-serverless-prototype/pull/81) で可能になったので同じ要領でおそらくイケると思う。

以前試した時はダメだったが、[こちら](https://github.com/dherault/serverless-offline/issues/153) に興味深い事例がある。

実際にTypeScriptでserverless-offlineを実行している例。
もしこれが上手く行けば、serverless-webpackを利用するのを辞めるのも一つの選択肢となる。

**Comment by keita-nishimoto** [comment]
デプロイ時の大きな変更がある模様。
https://github.com/serverless/serverless/pull/3344

おそらく問題はないが念の為、内容を詳しく確認しておく。

**Comment by horike37** [comment]
ローカル開発環境という意味では以下のプラグインも最近Serverless Framework界隈で人気です。 
https://github.com/serverless-community-labs/serverless-plugin-simulate

DockerでLambdaを立ち上げてAPI Gatewayもシュミレートしてくれるプラグインです。
僕はまだ試したことないのですが、こちらも試されると良いかもしれません。

**Comment by keita-nishimoto** [comment]
@horike37 

はじめまして。貴重な情報を頂きありがとうございます。

教えて頂いたプラグインを見たところCustom Authorizerの再現も可能そうなので、こちら試してみようと思います。https://github.com/keita-nishimoto/aws-serverless-prototype/issues/141

[教えて頂いたプラグイン](https://github.com/serverless-community-labs/serverless-plugin-simulate) を試した結果は何らかの形で公開しようかと思います。

話は変わりますが、現在TypeScriptで開発を行っている関係上、[serverless-webpack](https://github.com/elastic-coders/serverless-webpack) の開発状況も気になっております。

**Comment by horike37** [comment]
@keita-nishimoto 
はじめまして。

serverless-webpackの開発状況はちょっとわからないですね。それなりにちゃんとメンテナンスされているように見えますが。

>教えて頂いたプラグイン を試した結果は何らかの形で公開しようかと思います。
是非、楽しみにしてます！

こういう形で検証されてる内容を全部GitHubにあげてられるのがすごくおもしろいなとおもって、ついコメントしちゃいました！

**Comment by keita-nishimoto** [comment]
@horike37 

> こういう形で検証されてる内容を全部GitHubにあげてられるのがすごくおもしろいなとおもって、ついコメントしちゃいました！

コメントを頂き、とてもありがたく思ってます！今後 [Qiita](http://qiita.com/keita-nishimoto) でも情報を公開していく予定ですので、また良かったら見て頂きたいです！
